- name: PLAY01
  hosts: web
  tasks:
  - name: PLAY 01
    ansible.buildin.debug:
      msg: "i am from Playbook one"


- name: PLAY02
  hosts: web
  tasks:
  - name: PLAY 02
    ansible.buildin.debug:
      msg: "I am from Playbook two"