- name: variables to print
  hosts: web
  vars:
    ROLE: "DEVOPS ENGINEER"
    EXPERIANCE: "3"
    NAME: "DEEPAK"
  tasks:
  - name: print the information
    ansible.builtin.debug:
     msg: "Hi i am {{ROLE}}, and my experiance is {{EXPERIANCE}}years, and my name is {{NAME}}"