- name: Variables to print
  hosts: web
  vars:
    COURSE: "DEVOPS WITH AWS"
    DURATION: "120HRS"
    TRAINER: "SHIVA KUMAR"
  tasks:
    - name: print the information
      ansible.builtin.debug:
        msg: "Hi, I am learning {{{COURSE}}, Duration is {{DURATION}}, Trainer: {{TRAINER}}"