- name: Variables to print
  hosts: web
  vars: ##play level, all tasks in this play have access to this
    COURSE: "DEVOPS WITH AWS"
    DURATION: "120HRS"
    TRAINER: "SHIVA KUMAR"
  tasks:
    - name: print the information
      ansible.builtin.debug:
        msg: "Hi, I am learning {{COURSE}}, Duration is {{DURATION}}, Trainer: {{TRAINER}}"

    - name: print the information  
      vars: #task level variables
        COURSE: "Ansible" #here we are over-riding the VARIABLE
      ansible.builtin.debug:
        msg: "Hi, I am learning {{COURSE}}, Duration is {{DURATION}}, Trainer: {{TRAINER}}"

    #in the above task ansible gets printed
    - name: print the information
      ansible.builtin.debug:
        msg: "Hi, I am learning {{COURSE}}, Duration is {{DURATION}}, Trainer: {{TRAINER}}"