- name: check a number is less than 10 or not
  hosts: local
  connection: local
  vars_prompt:
  - name: num
    prompt: please enter number
    private: false
  tasks:
  - name: print this if less than 10
    ansible.builtin.debug:
      msg: "Given Number {{ num }} is less than 10"
    when: num < 10 #conditional expression
  
  - name: print this if greater than or equal to 10
    ansible.builtin.debug:
      msg: "Given Number {{ num }} greater than or equal to 10"
    when: num >= 10