- name: gathering  facts
  hosts: web
  become: yes
  tasks:
  - name: print the facts 
    ansible.builtin.debug:
      msg: "facts are: {{ ansible_facts }}" #variable is automattically will be seted i.e ansible_facts