- name: installing packages using loops
  hosts: web
  become: yes
  tasks:
  - name: installing packages one by one
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    loop:
    - mysql
    - nginx
    - postfix
