- name: installing some packages and removing packages
  hosts: web
  become: yes
  tasks:
  - name: installing packages one by one
    ansible.builtin.package:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
    loop:
    - { name: 'mysql', state: 'present'}
    - { name: 'nginx', state: 'absent'}
    - { name: 'postfix', state: 'absent'}