- name: demo on filters/functions
  hosts: local
  connection: local
  vars:
    course: "DEVOPS"
  tasks:
  - name: print the deault variable
    ansible.builtin.debug:
      msg: "Hello {{ course | default('Ansible') }}"

  - name: convert to upper case
    vars:
      greeting: "Hello Deepak"
    ansible.builtin.debug:
      msg: "{{ greeting | upper }}" 

  - name: convert to lower case
    vars:
      greeting: "Hello Deepak"
    ansible.builtin.debug:
      msg: "{{ greeting | lower }}" 
  
  - name: convert to unique
    vars:
      numbers: [1,2,4,5,3,2,1]
    ansible.builtin.debug:
      msg: "{{ numbers | unique }}"

  - name: finding min and max
    vars:
      numbers: [1,2,4,5,3,2,1]
    ansible.builtin.debug:
      msg: "Min: {{ numbers | min }}
            Max: {{ numbers | max }}"


  - name: convert map to list
    vars:
      course:
        name: "Devops with AWS"
        duration: 120
        trainer: "shiva"
    ansible.builtin.debug:
      msg: "{{ course | dict2items }}""