- name: demo on filters/functions
  hosts: local
  connection: local
  vars:
    course: "DEVOPS"
  tasks:
  - name: print the deault variable
    ansible.builtin.debug:
      msg: "Hello {{ course | default('Ansible') }}"