- name: create ec2-user and r53 records
  hosts: local
  connection: local
  vars:
    subnet_id: "subnet-0701ba77de21e8f70"
    sg_id: "sg-02bcc52c5f8cdeff8"
    ami_id: "ami-09c813fb71547fc4f"
    servers:
    - mysql
    - backend
    - frontend
    zone_id: "deepakaws.online"
  tasks:
  - name: create ec2-instance
    ansible.builtin.debug:
      msg: "Hello"


