

#ansible connecting with AWS and create the instance whatever we want
- name: create ec2 instance and r53 records
  hosts: local
  connection: local
  vars:
    subnet_id: "subnet-04394e3587e1e9d34" #In "Networking" tab
    security_id: "sg-05598edab15484e46" #In "Security" tab
    ami_id: "ami-09c813fb71547fc4f"  #In details tab
    instances:
    - mysql
    - frontend
    - backend
    zone: "deepakaws.online"
  tasks:
  - name: ansible to install boto3 and botocore
    ansible.builtin.pip:
      name:
      - boto3
      - botocore
      executable: pip3.9

  - name: create ec2 instance
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      vpc_subnet_id: "{{ subnet_id }}"
      instance_type: "t3.micro"
      security_group: "{{ security_id }}"
      image_id: "{{ ami_id }}"
    loop: "{{ instances }}"
    register: ec2_instances

  - name: print the output
    ansible.builtin.debug:
      msg: "{{ ec2_instances }}"

  - name: create r53 private records
    amazon.aws.route53:
      state: present
      zone: "{{ zone }}"
      record: "{{ item.item }}.{{ zone }}"  #mysql.deepakaws.online
      type: A
      ttl: 1
      value: "{{ item.instances[0].private_ip_address }}"
      wait: true
      overwrite: true
    loop: "{{ ec2_instances.results }}"  #if we have already records

  # - name: create r53 public record for frontend
  #   amazon.aws.route53:
  #     state: present
  #     zone: "{{ zone }}"
  #     record: "{{ item.item }}.{{ zone }}"  #mysql.deepakaws.online
  #     type: A
  #     ttl: 1
  #     value: "{{ item.instances[0].public_ip_address }}"
  #     wait: true
  #     overwrite: true
  #   loop: "{{ ec2_instances.results }}" 
  #   when: item.item == "frontend"

  



# when we run this script multiple times it checks whether the instances are created with given values or not
# if not it create the new instances
#if the values to script changes then it will genrate instances with given values accordingly


#to install python packages in ansible
#pip3.9 install boto3 botocore