- name: print the variables
  hosts: web
  tasks:
  - name: print the string
    vars:
      NAME: "LEKHANA"
    ansible.builtin.debug:
      msg: "Hi i am {{ NAME }}, my experiance is {{ EXP }} and my role is {{ ROLE }}"
  