- name: create ec2 instance and r53 records
  hosts: local
  connection: local
  vars:
    img_id: "ami-09c813fb71547fc4f"
    subnet_id: "subnet-0bd6e7f670e267e67"
    instances:
    - mysql
    - frontend
    - backend
    zone: deepakaws.online
  tasks:
  - name: create ec2 instance
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      instance_type: t3.micro
      image_id: "{{ img_id }}"
      vpc_subnet_id: "{{ subnet_id }}"
      wait: true
    loop: "{{ instances }}"
    register: ec2_instances

  - name: print the output
    ansible.builtin.debug:
      msg: "{{ ec2_instances }}"

  - name: create r53 private records
    amazon.aws.route53:
      state: present
      zone: "{{ zone }}"
      record: "{{ item.item }}.{{ zone }}"
      value: "{{ item.instances[0].private_ip_address }}"
      type: A
      ttl: 1
      wait: true
      overwrite: true
    loop: "{{ ec2_instances.results }}"

  - name: create r53 private records
    amazon.aws.route53:
      state: present
      zone: "{{ zone }}"
      record: "{{ zone }}"
      value: "{{ item.instances[0].private_ip_address }}"
      type: A
      ttl: 1
      wait: true
      overwrite: true
    loop: "{{ ec2_instances.results }}"
    when: item.item == "frontend"


